"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var xmlHttpRequestClient_1 = require("../app/http/xmlHttpRequestClient");
var settingsProvider_1 = require("../app/configuration/settingsProvider");
var defaultEventManager_1 = require("../app/events/defaultEventManager");
var defaultRouteHandler_1 = require("../app/routing/defaultRouteHandler");
var globalEventHandler_1 = require("../app/events/globalEventHandler");
var localCache_1 = require("../app/caching/localCache");
var permalinkService_1 = require("../app/permalinks/permalinkService");
var widgetService_1 = require("../app/widgets/widgetService");
var layoutService_1 = require("../app/layouts/layoutService");
var pageService_1 = require("../app/pages/pageService");
var blogService_1 = require("../app/blogs/blogService");
var newsService_1 = require("../app/news/newsService");
var fileService_1 = require("../app/files/fileService");
var mediaService_1 = require("../app/media/mediaService");
var navigationService_1 = require("../app/navigation/navigationService");
var siteService_1 = require("../app/sites/siteService");
var intercomService_1 = require("../app/intercom/intercomService");
var layoutModelBinder_1 = require("../app/widgets/layoutModelBinder");
var pageModelBinder_1 = require("../app/widgets/pageModelBinder");
var sectionModelBinder_1 = require("../app/widgets/sectionModelBinder");
var rowModelBinder_1 = require("../app/widgets/rowModelBinder");
var columnModelBinder_1 = require("../app/widgets/columnModelBinder");
var navbarModelBinder_1 = require("../app/widgets/navbarModelBinder");
var textblockModelBinder_1 = require("../app/widgets/textblockModelBinder");
var pictureModelBinder_1 = require("../app/widgets/pictureModelBinder");
var mapModelBinder_1 = require("../app/widgets/mapModelBinder");
var videoPlayerModelBinder_1 = require("../app/widgets/videoPlayerModelBinder");
var audioPlayerModelBinder_1 = require("../app/widgets/audioPlayerModelBinder");
var buttonModelBinder_1 = require("../app/widgets/buttonModelBinder");
var modelBinderSelector_1 = require("../app/widgets/modelBinderSelector");
var viewManager_1 = require("../app.ko/ui/viewManager");
var slateHtmlEditor_1 = require("../app/editing/paperslate/slateHtmlEditor");
var youtubeModelBinder_1 = require("../app.ko/editors/youtube-player/youtubeModelBinder");
var ComponentRegistrationCommon = (function () {
    function ComponentRegistrationCommon() {
    }
    ComponentRegistrationCommon.prototype.register = function (injector) {
        injector.bindSingleton("viewManager", viewManager_1.ViewManager);
        injector.bind("htmlEditor", slateHtmlEditor_1.SlateHtmlEditor);
        injector.bindSingleton("httpClient", xmlHttpRequestClient_1.XmlHttpRequestClient);
        injector.bindSingleton("settingsProvider", settingsProvider_1.SettingsProvider);
        injector.bindSingleton("eventManager", defaultEventManager_1.DefaultEventManager);
        injector.bindSingleton("routeHandler", defaultRouteHandler_1.DefaultRouteHandler);
        injector.bindSingleton("globalEventHandler", globalEventHandler_1.GlobalEventHandler);
        injector.bindSingleton("localCache", localCache_1.LocalCache);
        injector.bindFactory("permalinkService", function (ctx) {
            var objectStorage = ctx.resolve("objectStorage");
            return new permalinkService_1.PermalinkService(objectStorage);
        });
        injector.bindSingleton("widgetService", widgetService_1.WidgetService);
        injector.bindSingleton("layoutService", layoutService_1.LayoutService);
        injector.bindSingleton("pageService", pageService_1.PageService);
        injector.bindSingleton("blogService", blogService_1.BlogService);
        injector.bindSingleton("newsService", newsService_1.NewsService);
        injector.bindSingleton("fileService", fileService_1.FileService);
        injector.bindSingleton("mediaService", mediaService_1.MediaService);
        injector.bindSingleton("navigationService", navigationService_1.NavigationService);
        injector.bindSingleton("siteService", siteService_1.SiteService);
        injector.bindSingleton("intercomService", intercomService_1.IntercomService);
        injector.bind("layoutModelBinder", layoutModelBinder_1.LayoutModelBinder);
        injector.bind("pageModelBinder", pageModelBinder_1.PageModelBinder);
        injector.bind("sectionModelBinder", sectionModelBinder_1.SectionModelBinder);
        injector.bind("rowModelBinder", rowModelBinder_1.RowModelBinder);
        injector.bind("columnModelBinder", columnModelBinder_1.ColumnModelBinder);
        injector.bind("navbarModelBinder", navbarModelBinder_1.NavbarModelBinder);
        injector.bind("textModelBinder", textblockModelBinder_1.TextblockModelBinder);
        injector.bind("pictureModelBinder", pictureModelBinder_1.PictureModelBinder);
        injector.bind("mapModelBinder", mapModelBinder_1.MapModelBinder);
        injector.bind("youtubeModelBinder", youtubeModelBinder_1.YoutubeModelBinder);
        injector.bind("videoPlayerModelBinder", videoPlayerModelBinder_1.VideoPlayerModelBinder);
        injector.bind("audioPlayerModelBinder", audioPlayerModelBinder_1.AudioPlayerModelBinder);
        injector.bind("buttonModelBinder", buttonModelBinder_1.ButtonModelBinder);
        injector.bindFactory("modelBinderSelector", function (ctx) {
            var modelBinders = new Array();
            modelBinders.push(ctx.resolve("navbarModelBinder"));
            modelBinders.push(ctx.resolve("textModelBinder"));
            modelBinders.push(ctx.resolve("pictureModelBinder"));
            modelBinders.push(ctx.resolve("mapModelBinder"));
            modelBinders.push(ctx.resolve("youtubeModelBinder"));
            modelBinders.push(ctx.resolve("videoPlayerModelBinder"));
            modelBinders.push(ctx.resolve("audioPlayerModelBinder"));
            modelBinders.push(ctx.resolve("buttonModelBinder"));
            return new modelBinderSelector_1.ModelBinderSelector(modelBinders);
        });
    };
    return ComponentRegistrationCommon;
}());
exports.ComponentRegistrationCommon = ComponentRegistrationCommon;
