"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require("setimmediate");
var inversifyInjector_1 = require("./app/injection/inversifyInjector");
var components_common_1 = require("./registrations/components.common");
var components_widgets_1 = require("./registrations/components.widgets");
var components_editors_1 = require("./registrations/components.editors");
var knockout_common_1 = require("./registrations/knockout.common");
var knockout_widgets_1 = require("./registrations/knockout.widgets");
var knockout_editors_1 = require("./registrations/knockout.editors");
var knockout_loaders_1 = require("./registrations/knockout.loaders");
var registrations_firebase_1 = require("./app/firebase/registrations.firebase");
$(function () {
    var injector = new inversifyInjector_1.InversifyInjector();
    var use = function (module) {
        module.register(injector);
    };
    use(new components_common_1.ComponentRegistrationCommon());
    use(new components_widgets_1.ComponentRegistrationWidgets());
    use(new components_editors_1.ComponentRegistrationEditors());
    use(new knockout_loaders_1.KnockoutRegistrationLoaders());
    use(new knockout_common_1.KnockoutRegistrationCommon());
    use(new knockout_widgets_1.KnockoutRegistrationWidgets());
    use(new knockout_editors_1.KnockoutRegistrationEditors());
    use(new registrations_firebase_1.FirebaseRegistration(true));
    injector.resolve("globalEventHandler");
    injector.resolve("formattingTools");
    injector.resolve("hyperlinkTools");
    injector.resolve("contentBindingHandler");
    injector.resolve("gridBindingHandler");
    injector.resolve("lighboxBindingHandler");
    injector.resolve("draggablesBindingHandler");
    injector.resolve("widgetBindingHandler");
    injector.resolve("intercomService");
    ko.virtualElements.allowedBindings["widget"] = true;
    ko.virtualElements.allowedBindings["widgetH"] = true;
    ko.virtualElements.allowedBindings["layoutrow"] = true;
    ko.virtualElements.allowedBindings["component"] = true;
    ko.applyBindings();
});
